### PR TITLE
Copy button appears centered over text (rather than centered over label)

### PR DESCRIPTION
**Pull request by tomhoag**
I added an extension to UILabel to find the bounding box of the text in the label.  The bounding box is then used as the rect for the call to copyMenu.setTargetRect

I added a few labels to the example to illustrate.

Hope this is helpful!

### CODE REVIEW

**Comment by tomhoag** [comment]
Closing in lieu of a new request

**Comment by tomhoag** [comment]
re-opening with new commit

**Comment by dostu** [comment]
Thanks for contributing! I think it’s a valid use case. 

I’ve tested the code, and it works correctly. However, I’ve found a UILabel method which seems to do the same, called `textRect`. What do you think, could we use it here?

`textRect(forBounds: bounds, limitedToNumberOfLines: 0)`

**Comment by tomhoag** [comment]
Nice catch -- I've replaced the custom code with a call to .textRect

**Comment by dostu** [comment]
Looks great!

**Pull request merged**
